### ISSUE TITLE
responsive topnavbar not working properly

### ISSUE THREAD

**Issue by Pranay0302** [42ip/wwww#2]
![issue](https://user-images.githubusercontent.com/55592629/90178368-7176d680-ddc9-11ea-95d9-954bbb90fab6.gif)

**Comment by sonuishaq67** [comment]
Ahhh I'll try to work on this

**Comment by Pranay0302** [comment]
okay cool

**Comment by sonuishaq67** [comment]
found people with the same [problem](https://stackoverflow.com/questions/36110757/bootstrap-collapsed-menu-opening-then-immediately-collapsing-again ) but doesn't fix it

**Comment by sonuishaq67** [comment]
I also tried to reproduce a new bar and replacing it 
Still doesn't work
![Screenshot from 2020-08-17 20-48-54](https://user-images.githubusercontent.com/55189255/90412798-2b708a00-e0cb-11ea-8f24-dcbbc6e1f54b.png)
maybe ill change the bootstrap css ,js file

**Comment by Pranay0302** [comment]
yeah even i tried a lot of things and asked couple of members who are familiar with bootstrap in the discord server but even they were not able to resolve this issue

**Comment by sonuishaq67** [comment]
> yeah even i tried a lot of things and asked couple of members who are familiar with bootstrap in the discord server but even they were not able to resolve this issue 

I found the mistake 
Ill make a new branch and send a pr

**Comment by Pranay0302** [comment]
nice

**Comment by sonuishaq67** [comment]
Don't merge yet 
It's because of the jquery file
Dk how to fix it

**Comment by Pranay0302** [comment]
okay i'll look into it

**Comment by Pranay0302** [comment]
Okay so i merged it as it was working fine in a live server and now when i deployed it in the website, the navbar won't work.
**check it **

**Comment by Pranay0302** [comment]
okay so it works fine in live server and when i deployed the website it is not working lol
**check it**

**Comment by sonuishaq67** [comment]
only for the contact page right?

**Comment by sonuishaq67** [comment]
Deployed it 
Yup 
works fine now
